# Generated by Django 6.0.7 on 2026-07-27 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loaf',
            options={'verbose_name': 'Loaf', 'verbose_name_plural': 'Loaves'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loaf_comments', to=settings.AUTH_USER_MODEL)),
                ('loaf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracker.loaf')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
