# Generated by Django 6.0.7 on 2026-07-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_loaf_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='breadmachine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='machines/'),
        ),
        migrations.AddField(
            model_name='breadmachine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
